### General information

## Authoring

# Displayed site name
site_name: Fern Specification
# ?
site_author: Fern developers
# Site description (overridden by page descriptions)
site_description: Fern lang speccccc
# Site URL needed by the social plugin
# site_url: https://FlagHuner01.github.io/mkdocs-yml/
# Copyright notice in footer
copyright: |
    Copyright &copy; Fern Developers - 2024
     <br>   Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in the section entitled "GNU
    Free Documentation License".

## Git

# Git repository
repo_name: fern-pl/specification
# Enables page modification
edit_uri: https://github.com/fern-pl/specification/edit/main/specification/
docs_dir: "specification"


### Site layout

nav:
  - Home: index.md
  - Grammar: grammar.md  
  - Metaprogramming: metaprogramming.md
  - Model: model.md
  - Copyright: LICENSE.md
# concepts.md  fnc.md  grammar.md  index.md  lexical.md  metaprogramming.md  model.md


### Theme customization

theme:
  # Enable Material theme
  name: material

  # Font options
  font: 
    text: Roboto
    code: Roboto Mono
  
  # Language selection.
  # For multiple languages, create multiple projects and link them with the language selector
  language: en

  # Logo as an image
  #logo: assets/logo.png
  # logo as an icon
  # Find 'em here: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  icon:
    logo: material/rocket

  # Favicon can be set as an image
  #favicon:

  ## Color palette
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      #primary:
      #accent:

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      #primary:
      #accent:
  
  features:
    ## Site navigation

    # Single Page Application
    - navigation.instant
    # Automatic anchor update in URL
    - navigation.tracking
    # Tabs in the top menu
    - navigation.tabs
    # Breadcrumbs at the top of pages
    - navigation.path
    # Option to make overview pages for subfolders
    # This page must be subfoler/index.md
    - navigation.indexes
    # Sidebar following / opening as you read
    - toc.follow
    # Back-to-top button
    - navigation.top
    # Previous/Next links in footer
    - navigation.footer

    ## Site search

    # Auto completion
    - search.suggest
    # Match highlight
    - search.highlight

    ## Announcement bars

    # Option to mark the announcement as read
    - announce.dismiss

    ## Git page info
    
    # Button for page edition
    - content.action.edit

    ## Code

    # Copy code
    - content.code.copy
    # Line selection
    - content.code.select
    # Add annotations to code
    - content.code.annotate

    ## Content tabs

    # Linked content tabs
    - content.tabs.link

    ## Tooltips
    - content.tooltips  






