### General information

## Authoring

# Displayed site name
site_name: Fern Specification
# ?
site_author: Fern developers
# Site description (overridden by page descriptions)
site_description: Fern lang speccccc
# Site URL needed by the social plugin
# site_url: https://FlagHuner01.github.io/mkdocs-yml/
# Copyright notice in footer
copyright: |
    Copyright &copy; Fern Developers - 2024
     <br>   Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation.
    A copy of the license is included in the section entitled "Copyleft".

## Git

# Git repository
repo_name: fern-pl/specification
# Enables page modification
edit_uri: https://github.com/fern-pl/specification/edit/main/specification/
docs_dir: "specification"


### Site layout

nav:
  - Home: index.md
  - Grammar: grammar.md  
  - Metaprogramming: metaprogramming.md
  - Model: model.md
  - Copyleft: LICENSE.md


### Theme customization

theme:
  name: terminal





